version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: food_delivery
      POSTGRES_USER: root
      POSTGRES_PASSWORD: yXVrv9gZG5KuezXO
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: prod
    env_file:
      - ./server/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: prod
    env_file:
      - ./client/.env
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./nginx/privkey.pem:/etc/ssl/private/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
