version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: food_delivery
      POSTGRES_USER: root
      POSTGRES_PASSWORD: yXVrv9gZG5KuezXO
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
    ports:
      - "5000:5000"
    command: npm run start:dev

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm start

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./nginx/privkey.pem:/etc/ssl/private/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
